#!/bin/bash

# This is an installer for the plant monitoring system. 
# The installer must be in the plant monitoring git repo.
# It links the webroot to the webroot of the repository this installer is in.
# It links the usbsniper and serial_read.py to be start up scripts.
# It links the repo to be in /plants.
# It does not check if python, php, mysql, apache, or any similar programs are installed which are necessary. It only links.

plantHome="/plant"

exitMsg ()
{
    echo $1
    exit 1
}

# this is the directory of this installer script
# It should be in the git repo
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
base=$(basename $DIR)
path=$(fold $DIR)
#check if installer is in the git repo
if [ ! -d $DIR"/.git" ]; then
    exitMsg "installer needs to be in the git repository"
fi

#check if the git repo is in the plant home
#this is important for several absolute paths in the project
if [ $path != $plantHome ]; then
    if [ ! -d "$plantHome" ]; then
        sudo mkdir $plantHome || exitMsg "Unable to make plant directory"
    fi
    sudo ln -s $DIR $plantHome$base 
fi

#link to the webroot
while true; do
    read -p "What is the web root path?" www
    if [ -d $www ]; then
        echo "$www is not a directory"
        break
    fi
done
wwwpath=$(fold $www)
wwwbase=$(basename $www)
echo "I am going to back up the current webroot to $wwwpath-old"
sudo mv $www $wwwpath"-old" || exitMsg "Unable to make web root backup."
sudo ln -s $DIR"/webroot" $www || exitMsg "Unable to link webroot to repo's webroot."

#set up start up scripts
startupUsbsniper="/etc/init.d/usbsniper"
repoUsbsniper=$DIR"/bash/usbsniper"
sudo ln -s $repoUsbsniper $startupUsbsniper || exitMsg "Unable to link usbsniper to /etc/init.d/"
sudo chmod +x $startupUsbsniper || exitMsg "Unable to make usbsniper executable"
sudo chmod +x $repoUsbsniper || exitMsg "Unable to make usbsniper executable"
update-rc.d usbsniper defaults

startupSerialread="/etc/init.d/richmondAndHisFlashingLights"
repoSerialread=$DIR"/bash/richmondAndHisFlashingLights"
sudo ln -s $repoSerialread $startupSerialread || exitMsg "Unable to link richmondAndHisFlashingLights to /etc/init.d/"
sudo chmod +x $startupSerialread || exitMsg "Unable to make richmondAndHisFlashingLights executable"
sudo chmod +x $repoSerialread || exitMsg "Unable to make richmondAndHisFlashingLights executable"
update-rc.d richmondAndHisFlashingLights defaults
